export interface AddMeasurementModel{
    TemplateId: number,
    Name: string,
    MeasurementId: number,
    UnitId: number,
    PercentFormatId: number,
    CurrencyId: number,
    DecimalPlaces: number,
    DynamicChangeUnit: boolean,
    AutomaticRead: boolean,
    Expression: boolean,
    ExpressionValue: string,
    DeviceId: number,
    VariableId: number,
    UnitExpression: boolean,
    UnitExpressionValue: string,
    DeviceUnitId: number,
    SavePeriodId: number,
    ManualWrite: boolean,
    ManualWriteUnitId: number,
    Prediction: boolean,
    PredictionModeId: number,
    PredictionPeriodId: number,
    SpotPrices: boolean,
    SpotPricesGraphTypeId: number,
}